name: Android NDK Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up NDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: '25.1.8937393'

    - name: Compile C++ code
      run: |
        # Create output directory
        mkdir -p libs/arm64-v8a
        
        # Compile for arm64-v8a architecture
        $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++ \
        -I $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include \
        -I $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android \
        -fPIC -shared \
        -llog \
        -o libs/arm64-v8a/libtermexec.so \
        exec.cpp

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-libs
        path: libs/